package com.xjl.demo.entity;

/**
 * @date 2020/10/30 11:23
 *
 */

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.id
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.name
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.age
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.sex
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.address
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.phone
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.password
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.id
     *
     * @return the value of Employee.id
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.id
     *
     * @param id the value for Employee.id
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.name
     *
     * @return the value of Employee.name
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.name
     *
     * @param name the value for Employee.name
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.age
     *
     * @return the value of Employee.age
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.age
     *
     * @param age the value for Employee.age
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.sex
     *
     * @return the value of Employee.sex
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.sex
     *
     * @param sex the value for Employee.sex
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.address
     *
     * @return the value of Employee.address
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.address
     *
     * @param address the value for Employee.address
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.phone
     *
     * @return the value of Employee.phone
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.phone
     *
     * @param phone the value for Employee.phone
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.password
     *
     * @return the value of Employee.password
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.password
     *
     * @param password the value for Employee.password
     *
     * @mbggenerated Fri Oct 30 11:21:09 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}